### ISSUE TITLE
Add Autodesk Fusion 360

### ISSUE THREAD

**Issue by dakshshah96** [dakshshah96/awesome-startup-credits#6]
▶️ Autodesk provides Fusion 360 for startups generating less than $100k/year in total revenue. Read more at https://www.autodesk.com/campaigns/fusion-360-for-hobbyists

👋 Anyone new to GitHub or making their first PR is most welcome to take this up!

❗️Don't forget to read the [contribution guidelines](https://github.com/dakshshah96/awesome-startup-credits/blob/master/CONTRIBUTING.md) before making a PR.

**Comment by neilpanchal** [comment]
If it takes 20 seconds to add it yourself, you should go ahead and make the change. Contribution guidelines are *overkill* for a 1 page text document.

**Comment by dakshshah96** [comment]
IMHO, having a set of simple guidelines to make sure that the list is not arranged haphazardly is not overkill.

My first commit/pull request on GitHub was a tiny documentation change. It's not that I cannot add this myself, I want to keep this open for someone who's new to Git/GitHub.
